from __future__ import annotations

import asyncio
import json
import logging
import re
import time
import uuid
from contextvars import ContextVar
from dataclasses import dataclass, field
from typing import Any

from nanoharness.agents.registry import AgentCard, AgentRegistry
from nanoharness.core.context import AgentContext, Message
from nanoharness.core.event_store import DoneEvent
from nanoharness.core.nano_core import NanoCore
from nanoharness.provider.base import LLMProvider

log = logging.getLogger(__name__)

# ─── 深度保护：防止 Orchestrator 内部再嵌套 Orchestrator 无限递归 / Depth guard: prevent nested Orchestrator-from-Orchestrator infinite recursion ────
# 每个 asyncio Task 持有自己的副本，不同用户会话互不干扰（同 TurnRunner._LOCK_OWNER 设计）/ Each asyncio Task holds its own copy, different user sessions do not interfere (same as TurnRunner._LOCK_OWNER design)
_ORCHESTRATION_DEPTH: ContextVar[int] = ContextVar("_orchestration_depth", default=0)

# ─── 系统提示 / System prompts ─────────────────────────────────────────────────

_DECOMPOSE_SYSTEM = """\
你是任务分解专家。把用户的复杂任务拆成 2~5 个子任务。

分析子任务之间是否有顺序依赖：
- 如果子任务 B 必须用到子任务 A 的结果，在 B.depends_on 里填 A 的 index
- 没有依赖的子任务会并行执行；有依赖的等依赖完成后才启动
- 优先设计独立子任务（depends_on 为空），只有业务上必须串行时才加依赖

只输出 JSON，格式如下（子任务按 0、1、2… 顺序编号）：
{
  "subtasks": [
    {
      "index": 0,
      "description": "子任务的详细描述，包含足够的上下文",
      "required_capability": "需要的能力关键词（如 code_review / search / summarize / math）",
      "depends_on": []
    },
    {
      "index": 1,
      "description": "基于子任务 0 的结果进一步处理",
      "required_capability": "writing",
      "depends_on": [0]
    }
  ]
}

注意：
- 如果任务本身已经足够简单，输出 1 个子任务即可
- required_capability 要精确，这决定了哪个 Agent 会处理这个子任务
"""

_SYNTHESIZE_SYSTEM = """\
你是一个高级 AI 助手。以下是一个复杂任务被拆成子任务后，各个 Worker Agent 分别完成的结果。
请综合所有子任务的输出，给出一个完整、连贯的最终答复，不要重复每个子任务的标题。
"""


# ─── 数据模型 / Data models ──────────────────────────────────────────────────────

@dataclass
class SubtaskSpec:
    """Orchestrator 对一个子任务的描述，由 LLM 分解生成 / Orchestrator's description of a subtask, generated by LLM decomposition."""
    index: int
    description: str
    required_capability: str
    depends_on: list[int] = field(default_factory=list)   # 依赖的子任务 index 列表，为空则可立即并行执行 / list of dependency indices; empty means can run immediately in parallel


@dataclass
class SubtaskResult:
    """一个 Worker 完成子任务后的结果 / Result after a Worker completes a subtask."""
    spec: SubtaskSpec
    agent_id: str
    output: str
    success: bool
    elapsed_ms: float


@dataclass
class OrchestratorResult:
    """整个 Supervisor 编排的最终结果 / Final result of the whole Supervisor orchestration."""
    original_task: str
    subtask_results: list[SubtaskResult]
    final_synthesis: str
    total_elapsed_ms: float

    @property
    def succeeded_count(self) -> int:
        return sum(1 for r in self.subtask_results if r.success)


# ─── Orchestrator ─────────────────────────────────────────────────────────────

class Orchestrator:
    """
    Supervisor 模式编排器 / Supervisor-mode orchestrator.

    四步流程 / Four-step flow：
    1. 拆解（Decompose）：一次 T0 级 LLM call，把复杂任务分解为 N 个子任务规格（JSON）
    2. 路由（Route）：从 AgentRegistry 按 required_capability 匹配 AgentCard
    3. 执行（Execute）：asyncio.gather 并行 spawn N 个 Worker NanoCore，收集结果
    4. 综合（Synthesize）：T1 级 LLM call 把 N 份输出合并为最终答复

    面试话术 / Interview talking point：
    "Orchestrator 的核心是分离关注点：LLM 知道如何拆解任务（第一步），
    Registry 知道哪个 Agent 有对应能力（第二步），
    NanoCore 知道如何执行（第三步），三者互不耦合。
    asyncio.gather 保证独立子任务真并行，不是串行模拟。
    ContextVar 深度计数确保嵌套 Orchestrator 最多 max_depth 层，
    防止 Agent 无限 spawn Agent 耗尽资源。 / The core of Orchestrator is separation of concerns: the LLM knows how to decompose tasks (step 1), the Registry knows which Agent has the capability (step 2), and NanoCore knows how to execute (step 3); the three are decoupled. asyncio.gather guarantees truly parallel independent subtasks, not serial simulation. The ContextVar depth counter ensures nested Orchestrators go at most max_depth layers, preventing Agents from infinitely spawning Agents and exhausting resources."
    """

    def __init__(
        self,
        registry: AgentRegistry,
        provider_factory: dict[str, LLMProvider],   # tier_str → provider（如 {"T0": ..., "T1": ...}）/ tier_str → provider (e.g. {"T0": ..., "T1": ...})
        max_workers: int = 5,                        # 单次编排最多并发的 Worker 数 / max concurrent Workers per orchestration
        max_depth: int = 2,                          # 最大嵌套编排深度 / max nested orchestration depth
        fallback_capability: str = "general",        # 无能力匹配时的兜底标签 / fallback tag when no capability matches
    ) -> None:
        self._registry = registry
        self._providers = provider_factory
        self._max_workers = max_workers
        self._max_depth = max_depth
        self._fallback_capability = fallback_capability
        self._active_counts: dict[str, int] = {}   # agent_id → 当前活跃 Worker 数，用于负载感知路由 / agent_id → active worker count for load-aware routing

    async def run(
        self,
        task: str,
        parent_ctx: AgentContext,
    ) -> OrchestratorResult:
        """
        主入口。接受复杂任务，返回 OrchestratorResult / Main entry. Accepts a complex task and returns OrchestratorResult.
        parent_ctx 只用于继承 session_key 前缀（worker 会用新的 session_key）/ parent_ctx is only used to inherit the session_key prefix (workers use their own new session_key).
        """
        depth = _ORCHESTRATION_DEPTH.get()
        if depth >= self._max_depth:
            # 深度超限：不再拆解，直接交给兜底 Agent 执行原始任务 / Depth exceeded: no further decomposition, hand the original task directly to the fallback Agent
            log.warning("编排深度超限（%d/%d），降级为直接执行", depth, self._max_depth)
            result = await self._run_direct(task, parent_ctx.session_key)
            return OrchestratorResult(
                original_task=task,
                subtask_results=[result],
                final_synthesis=result.output,
                total_elapsed_ms=result.elapsed_ms,
            )

        t0 = time.monotonic()
        token = _ORCHESTRATION_DEPTH.set(depth + 1)

        try:
            # 1. 拆解任务 / 1. Decompose task
            decompose_provider = self._get_provider("T0")
            specs = await self._decompose(task, decompose_provider)
            specs = specs[: self._max_workers]   # 截断，避免瞬发过多 API call / truncate to avoid bursting too many API calls
            log.info("任务拆解完成: 共 %d 个子任务", len(specs))

            # 2+3. 路由 + 依赖感知执行：无依赖的子任务并行，有依赖的等待依赖完成后启动 / 2+3. Route + dependency-aware execution: independent subtasks run in parallel, deps wait
            results = await self._execute_with_deps(specs, parent_ctx.session_key)

            # 4. 综合 / 4. Synthesize
            synth_provider = self._get_provider("T1")
            synthesis = await self._synthesize(task, results, synth_provider)

            return OrchestratorResult(
                original_task=task,
                subtask_results=results,
                final_synthesis=synthesis,
                total_elapsed_ms=(time.monotonic() - t0) * 1000,
            )
        finally:
            _ORCHESTRATION_DEPTH.reset(token)

    # ── 拆解 / Decompose ───────────────────────────────────────────────────────────

    async def _decompose(self, task: str, provider: LLMProvider) -> list[SubtaskSpec]:
        """调用 LLM 把任务拆成子任务列表，解析失败时返回单任务兜底 / Call the LLM to split the task into a subtask list; on parse failure, fall back to a single task."""
        try:
            resp = await provider.complete(
                system=_DECOMPOSE_SYSTEM,
                messages=[Message(role="user", content=f"请拆解以下任务：\n\n{task}")],
                max_tokens=512,
            )
            data = _parse_json(resp.final_text)
        except Exception as exc:
            log.warning("任务拆解 LLM 调用失败: %s", exc)
            data = None

        if data is None:
            return [SubtaskSpec(0, task, self._fallback_capability)]

        raw = data.get("subtasks", [])
        specs: list[SubtaskSpec] = []
        for i, item in enumerate(raw):
            if isinstance(item, dict) and item.get("description"):
                raw_deps = item.get("depends_on", [])
                # 只保留合法索引（整数且在 [0, len(raw)) 范围内）/ Keep only valid indices (int within [0, len(raw)))
                deps = [int(d) for d in raw_deps if isinstance(d, (int, float)) and 0 <= int(d) < len(raw) and int(d) != i]
                specs.append(SubtaskSpec(
                    index=i,
                    description=item["description"],
                    required_capability=item.get("required_capability", self._fallback_capability),
                    depends_on=deps,
                ))

        return specs or [SubtaskSpec(0, task, self._fallback_capability)]

    # ── 路由 / Route ──────────────────────────────────────────────────────────────

    def _route(self, spec: SubtaskSpec) -> AgentCard:
        """
        按 required_capability 找 AgentCard，多级兜底保证永不失败 / Find an AgentCard by required_capability; multi-level fallback guarantees it never fails.
        有多个候选时选当前活跃任务最少的（负载感知）/ When multiple candidates exist, pick the least busy one (load-aware).
        """
        candidates = self._registry.lookup_by_capability(spec.required_capability)
        if not candidates:
            candidates = self._registry.lookup_by_capability(self._fallback_capability)
        if not candidates:
            return _FALLBACK_CARD
        # 负载感知：活跃 Worker 数最少的优先 / Load-aware: prefer candidate with fewest active workers
        return min(candidates, key=lambda c: self._active_counts.get(c.agent_id, 0))

    # ── 执行 Worker / Execute Worker ─────────────────────────────────────────────

    async def _run_worker(
        self,
        spec: SubtaskSpec,
        card: AgentCard,
        parent_session_key: str,
    ) -> SubtaskResult:
        """
        用 AgentCard 的配置 spawn 一个 Worker NanoCore 执行子任务 / Spawn a Worker NanoCore using the AgentCard config to execute the subtask.

        Worker 用独立 session_key（parent_key#worker-{i}-{hex}），
        避免与父 session 的 TurnRunner 锁产生冲突 / The Worker uses an independent session_key (parent_key#worker-{i}-{hex}) to avoid conflicting with the parent session's TurnRunner lock.
        """
        t0 = time.monotonic()
        worker_session = f"{parent_session_key}#worker-{spec.index}-{uuid.uuid4().hex[:6]}"

        # 负载计数：进入时 +1，退出时 -1（finally 保证） / Load tracking: +1 on entry, -1 on exit (guaranteed by finally)
        self._active_counts[card.agent_id] = self._active_counts.get(card.agent_id, 0) + 1
        try:
            provider = self._get_provider(card.default_tier)
            ctx = AgentContext(
                agent_id=card.agent_id,
                session_key=worker_session,
                system_prompt=card.system_prompt,
                model_id=provider.model_id,
            )
            core = NanoCore(
                ctx=ctx,
                provider=provider,
                tools=card.tools,
                tool_definitions=card.tool_definitions,
            )

            output = ""
            success = True
            try:
                async for event in core.run_turn(spec.description):
                    if isinstance(event, DoneEvent):
                        output = event.final_text
            except Exception as exc:
                success = False
                output = f"[Worker 错误: {exc}]"
                log.warning("子任务 %d (%s) 失败: %s", spec.index, card.agent_id, exc)
        finally:
            self._active_counts[card.agent_id] = max(0, self._active_counts.get(card.agent_id, 0) - 1)

        return SubtaskResult(
            spec=spec,
            agent_id=card.agent_id,
            output=output,
            success=success,
            elapsed_ms=(time.monotonic() - t0) * 1000,
        )

    async def _run_direct(self, task: str, parent_session_key: str) -> SubtaskResult:
        """深度超限时的降级路径：不拆解，直接执行 / Degraded path when depth is exceeded: no decomposition, execute directly."""
        spec = SubtaskSpec(0, task, self._fallback_capability)
        card = self._route(spec)
        return await self._run_worker(spec, card, parent_session_key)

    async def _execute_with_deps(
        self,
        specs: list[SubtaskSpec],
        parent_session_key: str,
    ) -> list[SubtaskResult]:
        """
        依赖感知执行 / Dependency-aware execution.

        depends_on 为空的子任务立即并行启动；depends_on 非空的等待所有依赖的 asyncio.Event 置位后才启动。
        检测到环路时降级为全并行（输出 WARNING）/ Falls back to full parallel on cycle detection (WARNING logged).

        面试话术 / Interview talking point:
        "每个子任务有一个 asyncio.Event，完成时 set()。
        有依赖的子任务先 await 所有依赖的 Event，再开始执行——一行代码实现拓扑调度。
        DFS 环路检测确保死锁不可能发生。
        / Each subtask has an asyncio.Event that is set() on completion.
        Subtasks with dependencies await their deps' Events before starting — topological scheduling in one line.
        DFS cycle detection ensures deadlocks are impossible."
        """
        if _has_cycle(specs):
            log.warning("检测到子任务依赖循环，降级为全并行执行 / Dependency cycle detected, falling back to full parallel")
            return list(await asyncio.gather(*[
                self._run_worker(spec, self._route(spec), parent_session_key)
                for spec in specs
            ]))

        done_events: dict[int, asyncio.Event] = {spec.index: asyncio.Event() for spec in specs}
        results: dict[int, SubtaskResult] = {}

        async def run_one(spec: SubtaskSpec) -> None:
            # 等待所有依赖完成 / Wait for all dependency subtasks to finish
            for dep_idx in spec.depends_on:
                if dep_idx in done_events:
                    await done_events[dep_idx].wait()
            card = self._route(spec)
            result = await self._run_worker(spec, card, parent_session_key)
            results[spec.index] = result
            done_events[spec.index].set()

        await asyncio.gather(*[run_one(spec) for spec in specs])
        return [results[spec.index] for spec in sorted(specs, key=lambda s: s.index)]

    # ── 综合 / Synthesize ──────────────────────────────────────────────────────────

    async def _synthesize(
        self,
        original_task: str,
        results: list[SubtaskResult],
        provider: LLMProvider,
    ) -> str:
        """把各子任务结果合并为连贯的最终答复 / Merge each subtask's result into a coherent final reply."""
        parts = [f"原始任务：{original_task}\n"]
        for r in results:
            status = "✓" if r.success else "✗"
            parts.append(f"子任务 {r.spec.index + 1} [{status}] {r.spec.description}\n{r.output}")
        prompt = "\n\n".join(parts)

        try:
            resp = await provider.complete(
                system=_SYNTHESIZE_SYSTEM,
                messages=[Message(role="user", content=prompt)],
                max_tokens=1024,
            )
            return resp.final_text
        except Exception as exc:
            log.warning("综合 LLM 调用失败，降级拼接: %s", exc)
            return "\n\n".join(
                f"[子任务 {r.spec.index + 1}]\n{r.output}" for r in results
            )

    # ── 内部工具 / Internal helpers ──────────────────────────────────────────────

    def _get_provider(self, tier: str) -> LLMProvider:
        """按档位取 provider，找不到时逐级向上兜底，仍未找到则 raise / Get a provider by tier; fall back level by level upward; raise if not found."""
        for t in [tier, "T1", "T0"]:
            p = self._providers.get(t)
            if p is not None:
                return p
        raise RuntimeError(f"provider_factory 中找不到 tier={tier} 或兜底档位，请检查配置")


# ─── 依赖图工具 / Dependency graph helpers ──────────────────────────────────────

def _has_cycle(specs: list[SubtaskSpec]) -> bool:
    """
    DFS 检测子任务依赖图中是否存在环路 / Detect cycles in the subtask dependency graph using DFS.
    有环时应降级为全并行，防止死锁 / On cycle, fall back to full parallel to prevent deadlock.
    """
    specs_by_idx: dict[int, SubtaskSpec] = {s.index: s for s in specs}
    visited: set[int] = set()
    visiting: set[int] = set()   # 当前 DFS 栈上的节点 / nodes currently on the DFS stack

    def dfs(idx: int) -> bool:
        if idx in visiting:
            return True     # 发现回边 → 有环 / back-edge found → cycle
        if idx in visited:
            return False
        visiting.add(idx)
        for dep in specs_by_idx.get(idx, SubtaskSpec(idx, "", "")).depends_on:
            if dfs(dep):
                return True
        visiting.discard(idx)
        visited.add(idx)
        return False

    return any(dfs(s.index) for s in specs)


# ─── 模块级常量 / Module-level constants ───────────────────────────────────────

_FALLBACK_CARD = AgentCard(
    agent_id="__fallback__",
    description="内置通用兜底 Agent，无任何 Agent 注册时使用",
    capabilities=["general"],
    system_prompt="你是一个通用助手，请尽力完成用户交代的任务。",
    default_tier="T1",
)


# ─── JSON 解析工具（与 LLMRouter / SessionConsolidator 保持一致的两步容错策略）/ JSON parsing helpers (two-step fault-tolerant strategy, consistent with LLMRouter / SessionConsolidator) ──

def _parse_json(text: str) -> dict | None:
    if not text:
        return None
    try:
        return json.loads(text.strip())
    except json.JSONDecodeError:
        pass
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group())
        except json.JSONDecodeError:
            pass
    return None
